### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by jwakely** [josuttis/belleviews#3]
The problem is not fixed.

You've added a copy of the licence file as `COPYRIGHT` and `COPYRIGHT.txt` but that file does not say anything about the copyright holders, it gives the terms under which the copyright holders allow you to use the code. It should be called COPYING3, by convention.

Every file containing GCC code needs to have the copyright notice and licence header restored. The terms of the licence require you to leave such notices intact. Removing them is a violation of the licence, and so is still a violation of copyright law.

The terms for distributing modified works based on the original code are at https://github.com/josuttis/belleviews/blob/main/COPYRIGHT.txt#L208

The files you've added to the repo say to put a comment like the following in the code, but you also need to retain the original copyright lines, *and* state that you've modified the code, and the date of such modifications. You should really get this code on a firm legal footing *before* making the repo public again.

```
   <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by josuttis** [comment]
I hope all necessary steps are done now
